### ISSUE TITLE
[Feature request] - slide over option

### ISSUE THREAD

**Issue by aikruger** [AnAngryRaven/obsidian-open-sidebar-on-hover#8]
It would be great to have the option to have the side bar slide over the main window without changing the layout of obsidian, only on clicking the side bar icon will it pin the side bar and make the resizing.

**Comment by unxok** [comment]
Try this. It doesn't handle anything to do with "pinning", but it will make it not disrupt the rest of the layout when it opens.

```css
.workspace-split.mod-horizontal.mod-sidedock.mod-left-split {
  position: absolute;
  left: var(--ribbon-width);
  z-index: var(--layer-sidedock);
  box-shadow: rgba(0, 0, 0, 0.5) 10px 0px 18px -2px;
}
```
